In [1]:
from splinter import Browser
from bs4 import BeautifulSoup as bs
import pandas as pd
import time
import funcs

# Data Collection

In [599]:
browser = Browser('chrome')

In [600]:
url = 'https://www.ncaa.com/stats/basketball-men/d1'
browser.visit(url)

In [601]:
url = 'https://www.ncaa.com/stats/basketball-men/d1'
browser.visit(url)
# home page tables (top_ten)
html = browser.html
tables = pd.read_html(html)
#save top ten tables
team_scoring_offense = tables[0]
team_scoring_defense = tables[1]
player_APG = tables[2]
player_RPG = tables[3]

In [605]:
team_scoring_offense

   Rank            Team   PPG
0     1         Gonzaga  86.1
1     2          Toledo  85.4
2     3    Oral Roberts  83.3
3     4   Southern Utah  82.8
4     5  Youngstown St.  81.9
5     6         Arizona  81.9
6     7         Alabama  81.8
7     8        Marshall  81.8
8     9         Cornell  81.7
9    10          Xavier  80.9

In [ ]:
#call get_team_offense to create df 
merged_df = funcs.get_team_offense()

#dictionary storing all the stat categories and their url numbers
url_dict = {
    'AST/TO':'474',
    'AST_PG':'216',
    'Bench_PPG':'1284',
    'Blocks_PG':'214',
    'Effect_FGPCT':'1288',
    'Fst_Brk_PPG':'1285',
    'FG_PCT':'148',
    'FG_PCT_DEF':'149',
    'Foul_PG':'286',
    'FF_Attempts_PG':'638',
    'FF_PCT':'150',
    'FF_':'149',
    'FF_Made_PG':'633',
    'RB_MAR':'151',
    'RB_DEF':'859',
    'RB_OFF':'857',
    'RB_PG':'932',
    'Scr_DEF':'146',
    'Scr_MAR':'147',
    'SCR_OFF':'145',
    'STL:PG':'215',
    '3FG_Attempts_PG':'625',
    '3FG_PCT':'152',
    '3FG_PCT_DEF':'518',
    '3FG_PG':'153',
    'TO_MAR':'519',
    'TO_FCD':'931',
    'TO_PG':'217',
    'Win_PCT':'168'
}

#list for the url in for loop in get_all_stats()
num_list = [value for value in url_dict.values()]

In [441]:
### Scrapes www.ncaa.com for mens basketball stats & returns dataframe
# all_stats = funcs.get_all_stats(num_list, merged_df)
# all_stats

Starting web scrape..
Last page reached for ASSIST/TURNOVER RATIO
Moving to next stat category...
Last page reached for ASSISTS PER GAME
Moving to next stat category...
Last page reached for BENCH POINTS PER GAME
Moving to next stat category...
Last page reached for BLOCKS PER GAME
Moving to next stat category...
Last page reached for EFFECTIVE FG PCT
**DEBUG**
 except clause on pd.merge.
 stat_category: EFFECTIVE FG PCT
 url_num:1288
Moving to next stat category...
Last page reached for FASTBREAK POINTS
Moving to next stat category...
Last page reached for FIELD GOAL PERCENTAGE
Moving to next stat category...
Last page reached for FIELD GOAL PERCENTAGE DEFENSE
Moving to next stat category...
Last page reached for FOULS PER GAME
Moving to next stat category...
Last page reached for FREE THROW ATTEMPTS PER GAME
Moving to next stat category...
Last page reached for FREE THROW PERCENTAGE
Moving to next stat category...
Last page reached for FIELD GOAL PERCENTAGE DEFENSE
Moving to next stat category...
Last page reached for FREE THROWS MADE PER GAME
Moving to next stat category...
Last page reached for REBOUND MARGIN
Moving to next stat category...
Last page reached for REBOUNDS (DEFENSIVE) PER GAME
Moving to next stat category...
Last page reached for REBOUNDS (OFFENSIVE) PER GAME
Moving to next stat category...
Last page reached for REBOUNDS PER GAME
Moving to next stat category...

C:\Users\Stan\AppData\Local\Temp\ipykernel_10092\10773407.py:50: FutureWarning: Passing 'suffixes' which cause duplicate columns {'RPG_x'} in the result is deprecated and will raise a MergeError in a future version.
  merged_df = pd.merge(merged_df,df, on = ['Team','GM']).drop(columns = ['Rank_x','Rank_y'])
C:\Users\Stan\AppData\Local\Temp\ipykernel_10092\10773407.py:54: FutureWarning: Passing 'suffixes' which cause duplicate columns {'RPG_x'} in the result is deprecated and will raise a MergeError in a future version.
  merged_df = pd.merge(merged_df,df, on = ['Team','GM']).drop(columns = 'Rank')

Last page reached for SCORING DEFENSE
Moving to next stat category...
Last page reached for SCORING MARGIN
Moving to next stat category...

C:\Users\Stan\AppData\Local\Temp\ipykernel_10092\10773407.py:50: FutureWarning: Passing 'suffixes' which cause duplicate columns {'PPG_x'} in the result is deprecated and will raise a MergeError in a future version.
  merged_df = pd.merge(merged_df,df, on = ['Team','GM']).drop(columns = ['Rank_x','Rank_y'])
C:\Users\Stan\AppData\Local\Temp\ipykernel_10092\10773407.py:54: FutureWarning: Passing 'suffixes' which cause duplicate columns {'PPG_x'} in the result is deprecated and will raise a MergeError in a future version.
  merged_df = pd.merge(merged_df,df, on = ['Team','GM']).drop(columns = 'Rank')

Last page reached for SCORING OFFENSE
Moving to next stat category...
Last page reached for STEALS PER GAME
Moving to next stat category...
Last page reached for THREE POINT ATTEMPTS PER GAME
Moving to next stat category...
Last page reached for THREE POINT PERCENTAGE
Moving to next stat category...
Last page reached for THREE POINT PERCENTAGE DEFENSE
Moving to next stat category...
Last page reached for THREE POINTERS PER GAME
Moving to next stat category...

C:\Users\Stan\AppData\Local\Temp\ipykernel_10092\10773407.py:50: FutureWarning: Passing 'suffixes' which cause duplicate columns {'3FG_x'} in the result is deprecated and will raise a MergeError in a future version.
  merged_df = pd.merge(merged_df,df, on = ['Team','GM']).drop(columns = ['Rank_x','Rank_y'])
C:\Users\Stan\AppData\Local\Temp\ipykernel_10092\10773407.py:54: FutureWarning: Passing 'suffixes' which cause duplicate columns {'3FG_x'} in the result is deprecated and will raise a MergeError in a future version.
  merged_df = pd.merge(merged_df,df, on = ['Team','GM']).drop(columns = 'Rank')

Last page reached for TURNOVER MARGIN
Moving to next stat category...
Last page reached for TURNOVERS FORCED PER GAME
Moving to next stat category...

C:\Users\Stan\AppData\Local\Temp\ipykernel_10092\10773407.py:50: FutureWarning: Passing 'suffixes' which cause duplicate columns {'Avg_x'} in the result is deprecated and will raise a MergeError in a future version.
  merged_df = pd.merge(merged_df,df, on = ['Team','GM']).drop(columns = ['Rank_x','Rank_y'])
C:\Users\Stan\AppData\Local\Temp\ipykernel_10092\10773407.py:54: FutureWarning: Passing 'suffixes' which cause duplicate columns {'Avg_x'} in the result is deprecated and will raise a MergeError in a future version.
  merged_df = pd.merge(merged_df,df, on = ['Team','GM']).drop(columns = 'Rank')

Last page reached for TURNOVERS PER GAME
Moving to next stat category...
Last page reached for WINNING PERCENTAGE
**DEBUG**
 except clause on pd.merge.
 stat_category: WINNING PERCENTAGE
 url_num:168

,Team,GM,PTS_x,PPG_x,AST_x,TO_x,Ratio_x,AST_y,APG,Bench,...,Opp TO_x,TO_y,Ratio_y,Opp TO_y,Avg_y,TO,TOPG,W,L,Pct
0,Gonzaga,37,3187,86.1,602,397,1.52,602,16.3,769,...,489,397,2.5,489,13.22,397,10.7,31,6,83.8
1,Toledo,35,2989,85.4,521,336,1.55,521,14.9,534,...,452,336,3.3,452,12.91,336,9.6,27,8,77.1
2,Oral Roberts,35,2915,83.3,514,329,1.56,514,14.7,693,...,445,329,3.3,445,12.71,329,9.4,30,5,85.7
3,Southern Utah,37,3064,82.8,485,492,0.99,485,13.1,783,...,527,492,0.9,527,14.24,492,13.3,24,13,64.9
4,Youngstown St.,34,2785,81.9,521,376,1.39,521,15.3,639,...,438,376,1.8,438,12.88,376,11.1,24,10,70.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,Cal Poly,33,2006,60.8,341,457,0.75,341,10.3,627,...,408,457,-1.5,408,12.36,457,13.8,8,25,24.2
348,CSU Bakersfield,33,1995,60.5,355,424,0.84,355,10.8,462,...,445,424,0.6,445,13.48,424,12.8,11,22,33.3
349,Green Bay,32,1898,59.3,350,447,0.78,350,10.9,479,...,342,447,-3.3,342,10.69,447,14.0,3,29,9.4
350,Florida A&M,29,1700,58.6,280,464,0.60,280,9.7,616,...,363,464,-3.5,363,12.52,464,16.0,7,22,24.1
351,California,32,1866,58.3,308,417,0.74,308,9.6,506,...,332,417,-2.7,332,10.38,417,13.0,3,29,9.4

# Data Clean-up

In [598]:
#view all col in returned df
# all_stats.columns

Index(['Team', 'GM', 'PTS_x', 'PPG_x', 'AST_x', 'TO_x', 'Ratio_x', 'AST_y',
       'APG', 'Bench', 'PPG_y', 'BLKS', 'BKPG', 'G', 'FGM_x', '3FG_x', 'FGA_x',
       'Pct_x', 'FB pts', 'PPG_x.1', 'FGM_y', 'FGA_y', 'FG%', 'OPP FG_x',
       'OPP FGA_x', 'OPP FG%_x', 'Fouls', 'PFPG', 'DQ', 'FT_x', 'FTA_x',
       'Avg_x', 'FT_y', 'FTA_y', 'FT%', 'OPP FG_y', 'OPP FGA_y', 'OPP FG%_y',
       'FT', 'FTA', 'Avg_y', 'REB_x', 'RPG_x', 'OPP REB', 'OPP RPG', 'REB MAR',
       'DRebs_x', 'RPG_y', 'ORebs_x', 'RPG_x.1', 'ORebs_y', 'DRebs_y', 'REB_y',
       'RPG_y.1', 'OPP PTS_x', 'OPP PPG_x', 'PTS_y', 'PPG_y.1', 'OPP PTS_y',
       'OPP PPG_y', 'SCR MAR', 'PTS', 'PPG', 'ST', 'STPG', '3FG_y', '3FGA_x',
       'Avg_x.1', '3FG_x.1', '3FGA_y', '3FG%', 'Opp 3FGA', 'Opp 3FG', 'Pct_y',
       '3FG_y.1', '3PG', 'Opp TO_x', 'TO_y', 'Ratio_y', 'Opp TO_y', 'Avg_y.1',
       'TO', 'TOPG', 'W', 'L', 'Pct'],
      dtype='object')

In [483]:
#### rename columns with identical name(name, name.1, name.2, etc)
#### solution found @
#### https://stackoverflow.com/questions/24685012/pandas-dataframe-renaming-multiple-identically-named-columns
# cols=pd.Series(all_stats.columns)
# for dup in cols[cols.duplicated()].unique(): 
#     cols[cols[cols == dup].index.values.tolist()] = [dup + '.' + str(i) if i != 0 else dup for i in range(sum(cols == dup))]


# all_stats = all_stats.columns=cols

In [581]:
#### create copy to manipulate
# all_stats1 = all_stats.copy()

In [582]:
#### remove duplicate columns
# all_stats1 = all_stats1.drop(columns= ['PTS','PPG','AST_y',
#                                        'G','FGM_x','3FG_x',
#                                        'FGA_x','FT_y','FTA_y',
#                                        'FT','FTA','Avg_y',
#                                        'OPP FG_y', 'OPP FGA_y',
#                                        'OPP FG%_y','ORebs_y',
#                                        'DRebs_y','REB_y', 'RPG_y.1',
#                                        'OPP PTS_x','PTS_y','PPG_y.1',
#                                        'OPP PPG_x','Avg_x.1', '3FG_x.1',
#                                        '3FGA_y','3FG_y.1','Opp TO_x', 'TO_y',])

In [584]:
#### rename columns so they make more sense
# all_stats1 = all_stats1.rename(columns = {"GM":'GP',
#                                         "PTS_x":"PTS",
#                                         "PPG_x":"PPG",
#                                          "AST_x":"AST",
#                                          "TO_x":"TO",
#                                          "Ratio_x":"AST/TO",
#                                           "PPG_y":"Bench_PPG",
#                                           "Pct_x":"EFF_FG_PCT",
#                                           "PPG_x.1":"FB_PPG",
#                                           "FGM_y":"FGM",
#                                           "FGA_y":"FGA",
#                                           "OPP FG_x":"OPP FG",
#                                           'OPP FGA_x':'OPP FGA',
#                                           'OPP FG%_x':'OPP FG%',
#                                           'FTA_x':'FTA',
#                                           'FT_x':"FT",
#                                           'Avg_x':'FTAvgAtt',
#                                           'REB_x':'REB',
#                                           'RPG_x':'RPG',
#                                           'DRebs_x':'DRebs',
#                                           'RPG_y':'DRPG',
#                                           'ORebs_x':'OReb',
#                                           'RPG_x.1':'ORPG',
#                                           'OPP PTS_y':'OPP PTS',
#                                           'OPP PPG_y':'OPP PPG',
#                                           '3FG_y':'3FG',
#                                           '3FGA_x':'3FGA',
#                                           'Pct_y':'OPP_3FG%',
#                                           'Ratio_y':'TO_RATIO',
#                                           'Opp TO_y':'OPP TO',
#                                           'Avg_y.1':'AVG_FCD_TO',
#                                         })

## Export Data to csv

In [587]:
#### save df to csv
# all_stats1.to_csv('../Resources/combined_stats.csv', index = False)

In [596]:
# read in csv to check 
combined_stats_df = pd.read_csv('../Resources/combined_stats.csv')

combined_stats_df

,Team,GP,PTS,PPG,AST,TO,AST/TO,APG,Bench,Bench_PPG,...,OPP_3FG%,3PG,TO_RATIO,OPP TO,AVG_FCD_TO,TO.1,TOPG,W,L,Pct
0,Gonzaga,37,3187,86.1,602,397,1.52,16.3,769,20.78,...,34.9,7.5,2.5,489,13.22,397,10.7,31,6,83.8
1,Toledo,35,2989,85.4,521,336,1.55,14.9,534,15.26,...,36.6,8.6,3.3,452,12.91,336,9.6,27,8,77.1
2,Oral Roberts,35,2915,83.3,514,329,1.56,14.7,693,19.80,...,34.7,10.7,3.3,445,12.71,329,9.4,30,5,85.7
3,Southern Utah,37,3064,82.8,485,492,0.99,13.1,783,21.16,...,34.7,8.5,0.9,527,14.24,492,13.3,24,13,64.9
4,Youngstown St.,34,2785,81.9,521,376,1.39,15.3,639,18.79,...,34.1,8.0,1.8,438,12.88,376,11.1,24,10,70.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,Cal Poly,33,2006,60.8,341,457,0.75,10.3,627,19.00,...,34.1,5.5,-1.5,408,12.36,457,13.8,8,25,24.2
348,CSU Bakersfield,33,1995,60.5,355,424,0.84,10.8,462,14.00,...,34.2,4.3,0.6,445,13.48,424,12.8,11,22,33.3
349,Green Bay,32,1898,59.3,350,447,0.78,10.9,479,14.97,...,35.0,6.8,-3.3,342,10.69,447,14.0,3,29,9.4
350,Florida A&M,29,1700,58.6,280,464,0.60,9.7,616,21.24,...,33.3,5.8,-3.5,363,12.52,464,16.0,7,22,24.1
351,California,32,1866,58.3,308,417,0.74,9.6,506,15.81,...,33.4,4.9,-2.7,332,10.38,417,13.0,3,29,9.4

## Below are old funcs..combined into funcs.get_all_stats()

In [277]:
# get scoring_offense, scoring_defense, player_APG, and player RPG for everyteam
# team scoring offense
def get_team_win_percent():
    browser = Browser('chrome')
    time.sleep(1)
    url = f'https://www.ncaa.com/stats/basketball-men/d1/current/team/168'
    browser.visit(url)
    time.sleep(2)
    counter = 2

    html = browser.html
    win_perc_soup = bs(html)

    pages_list = win_perc_soup.find_all('li', class_ = 'stats-pager__li')
    pages = len(pages_list) - 1

    for x in range(pages):
        #scrape table from first page then go to next page
        html = browser.html
        table = pd.read_html(html)

        if x > 0:
            df2 = table[0]
            df = pd.concat([df,df2]).reset_index().drop(columns = 'index')
        else:
            df = table[0]

        try:
            browser.links.find_by_href(f"/stats/basketball-men/d1/current/team/168/p{counter}").click()
            time.sleep(2)
        except:
            print('Last page reached for team win percentage..')

        counter +=1
    browser.quit()
    return df
#scrape table from first page then go to next page

In [278]:
# get scoring_offense, scoring_defense, player_APG, and player RPG for everyteam
# team scoring offense
def get_team_bench_points():
    browser = Browser('chrome')
    time.sleep(1)
    url = 'https://www.ncaa.com/stats/basketball-men/d1/current/team/1284'
    browser.visit(url)
    time.sleep(1)
    counter = 2

    html = browser.html
    bench_points_soup = bs(html)

    pages_list = bench_points_soup.find_all('li', class_ = 'stats-pager__li')
    pages = len(pages_list) - 1

    for x in range(pages):
        #scrape table from first page then go to next page
        html = browser.html
        table = pd.read_html(html)

        if x > 0:
            df2 = table[0]
            df = pd.concat([df,df2]).reset_index().drop(columns = 'index')
        else:
            df = table[0]

        try:
            browser.links.find_by_href(f"/stats/basketball-men/d1/current/team/1284/p{counter}").click()
            time.sleep(1)
        except:
            print('Last page reached for team bench points..')

        counter +=1
    browser.quit()
    return df
#scrape table from first page then go to next page

In [279]:
# get scoring_offense, scoring_defense, player_APG, and player RPG for everyteam
# team scoring offense
def get_team_rebounds():
    browser = Browser('chrome')
    time.sleep(1)
    url = 'https://www.ncaa.com/stats/basketball-men/d1/current/team/932'
    browser.visit(url)
    time.sleep(1)
    counter = 2

    html = browser.html
    rebounds_soup = bs(html)

    pages_list = rebounds_soup.find_all('li', class_ = 'stats-pager__li')
    pages = len(pages_list) - 1

    for x in range(pages):
        #scrape table from first page then go to next page
        html = browser.html
        table = pd.read_html(html)

        if x > 0:
            df2 = table[0]
            df = pd.concat([df,df2]).reset_index().drop(columns = 'index')
        else:
            df = table[0]

        try:
            browser.links.find_by_href(f"/stats/basketball-men/d1/current/team/932/p{counter}").click()
            time.sleep(1)
        except:
            print('Last page reached for team rebounds..')

        counter +=1
    browser.quit()
    return df
#scrape table from first page then go to next page

In [280]:
# get scoring_offense, scoring_defense, player_APG, and player RPG for everyteam
# team scoring offense
def get_team_assists():
    browser = Browser('chrome')
    time.sleep(1)
    url = 'https://www.ncaa.com/stats/basketball-men/d1/current/team/216'
    browser.visit(url)
    time.sleep(1)
    counter = 2

    html = browser.html
    assists_soup = bs(html)

    pages_list = assists_soup.find_all('li', class_ = 'stats-pager__li')
    pages = len(pages_list) - 1

    for x in range(pages):
        #scrape table from first page then go to next page
        html = browser.html
        table = pd.read_html(html)

        if x > 0:
            df2 = table[0]
            df = pd.concat([df,df2]).reset_index().drop(columns = 'index')
        else:
            df = table[0]

        try:
            browser.links.find_by_href(f"/stats/basketball-men/d1/current/team/216/p{counter}").click()
            time.sleep(1)
        except:
            print('Last page reached for team assists..')

        counter +=1
    browser.quit()
    return df
#scrape table from first page then go to next page

In [281]:
# get scoring_offense, scoring_defense, player_APG, and player RPG for everyteam
# team scoring offense
def get_team_defense():
    browser = Browser('chrome')
    time.sleep(1)
    url = 'https://www.ncaa.com/stats/basketball-men/d1'
    browser.visit(url)
    time.sleep(1)
    # from homepage, click on scoring offense link
    browser.links.find_by_partial_text('Scoring Defense').click()
    time.sleep(1)
    counter = 2

    html = browser.html
    scoring_defense_soup = bs(html)

    pages_list = scoring_defense_soup.find_all('li', class_ = 'stats-pager__li')
    pages = len(pages_list) - 1

    for x in range(pages):
        #scrape table from first page then go to next page
        html = browser.html
        table = pd.read_html(html)

        if x > 0:
            df2 = table[0]
            df = pd.concat([df,df2]).reset_index().drop(columns = 'index')
        else:
            df = table[0]

        try:
            browser.links.find_by_href(f"/stats/basketball-men/d1/current/team/146/p{counter}").click()
            time.sleep(1)
        except:
            print('Last page reached for team defense..')

        counter +=1
    browser.quit()
    return df
#scrape table from first page then go to next page

In [283]:
def merge_dfs(df1,df2,df3,df4,df5,df6):
    df_list = [df3,df4,df5]
    
    merged_df = pd.merge(df1,df2, on = ['Team','GM']).drop(columns = ['Rank_x','Rank_y'])
    
    for df in df_list:
        merged_df = pd.merge(merged_df, df,on = ['Team', "GM"]).drop(columns = 'Rank')
        
    merged_df = pd.merge(merged_df,df6, on = ['Team']).drop(columns = 'Rank')
    merged_df = merged_df.rename(columns = {'PPG_x':'PPG','PPG_y':'Bench_PPG'})
    
    return merged_df

In [284]:
def get_stats():
    team_scoring_offense = get_team_offense()
    team_scoring_defense = get_team_defense()
    team_assists = get_team_assists()
    team_rebounds = get_team_rebounds()
    team_bench_points = get_team_bench_points()
    team_win_percent = get_team_win_percent()
    
    merged_df = merge_dfs(
                        team_scoring_offense,
                        team_scoring_defense,
                        team_assists,
                        team_rebounds,
                        team_bench_points,
                        team_win_percent
                        )
    
    return merged_df

In [234]:
browser.quit()